# Generated by Django 4.0.3 on 2022-04-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_todo_todo_due_alter_todo_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Todo_due',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Todo_title',
            field=models.TextField(),
        ),
    ]
